#!/usr/bin/python3
#+
# Example use of anim_framework: Copy code out of README to make sure it works.
#
# Copyright 2015 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
from qahirah import \
    Colour, \
    Vector
from anim import \
    common, \
    lissa

anim_duration = 10.0
dimensions = Vector(1280, 720)
frame_rate = 25.0
nr_steps = 500

lissa = lissa.make_draw \
  (
    x_amp = 300,
    x_freq = 2,
    x_phase = common.linear_interpolator(0, anim_duration, 0, 1),
    y_amp = 300,
    y_freq = 3,
    y_phase = 0,
    nr_steps = nr_steps,
  )

def anim_init(g) :
    g.translate(dimensions / 2)
    g.source_colour = Colour.grey(1)
    g.paint()
    g.source_colour = Colour.from_hsva((0.25, 0.9, 0.9))
    g.line_width = 4
#end anim_init

def init_frame1(g, t) :
    g.source_colour = Colour.grey(1)
    g.paint()
    g.source_colour = Colour.from_hsva((0.25, 0.9, 0.9))
#end init_frame

init_frame = common.make_draw \
  (
    ("set_source_colour", (Colour.grey(1),)),
    ("paint", ()),
    (
        "set_source_colour",
        (
            common.hsva_to_colour_interpolator
              (
                h = common.linear_interpolator(0, anim_duration, 0, 1),
                s = 0.9,
                v = 0.9,
                a = 1
              ),
        )
    ),
  )

common.render_anim \
  (
    dimensions = dimensions,
    start_time = 0.0,
    end_time = anim_duration,
    frame_rate = frame_rate,
    draw_frame = common.draw_compose(init_frame, lissa),
    overall_presetup = anim_init,
    out_dir = "frames",
    start_frame_nr = 1
  )
